//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class nastan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nastan()
        {
            this.kartis = new HashSet<karti>();
        }
    
        public int id_nastan { get; set; }
        public int fk_id_komintent { get; set; }
        public int o_id_objekt { get; set; }
        public string naziv { get; set; }
        public string vreme { get; set; }
        public string slika { get; set; }
        public string cas { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string kratok_opis { get; set; }
        public string sirok_opis { get; set; }
        public string sajt { get; set; }
        public string video { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<karti> kartis { get; set; }
        public virtual komintent komintent { get; set; }
        public virtual objekt objekt { get; set; }
    }
}
