//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFCTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class onlinebookingDBContext : DbContext
    {
        public onlinebookingDBContext()
            : base("name=onlinebookingDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<karti> kartis { get; set; }
        public virtual DbSet<klient> klients { get; set; }
        public virtual DbSet<komintent> komintents { get; set; }
        public virtual DbSet<nastan> nastans { get; set; }
        public virtual DbSet<objekt> objekts { get; set; }
        public virtual DbSet<prodazba> prodazbas { get; set; }
        public virtual DbSet<statistika> statistikas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
