//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class klient
    {
        public klient()
        {
            this.prodazbas = new HashSet<prodazba>();
            this.kartis = new HashSet<karti>();
        }
    
        public int id_klient { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public Nullable<int> isadmin { get; set; }
    
        public virtual ICollection<prodazba> prodazbas { get; set; }
        public virtual ICollection<karti> kartis { get; set; }
    }
}
