//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class komintent
    {
        public komintent()
        {
            this.nastans = new HashSet<nastan>();
        }
    
        public int id_komintent { get; set; }
        public string opis { get; set; }
    
        public virtual ICollection<nastan> nastans { get; set; }
    }
}
