//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OBModel : DbContext
    {
        public OBModel()
            : base("name=OBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<karti> kartis { get; set; }
        public DbSet<klient> klients { get; set; }
        public DbSet<komintent> komintents { get; set; }
        public DbSet<nastan> nastans { get; set; }
        public DbSet<objekt> objekts { get; set; }
        public DbSet<prodazba> prodazbas { get; set; }
        public DbSet<statistika> statistikas { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
