//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class kosnicka
    {
        public int id_kosnicka { get; set; }
        public int fk_id_karti { get; set; }
        public int fk_id_klient { get; set; }
    }
}
