//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class nastan
    {
        private string opis;
        private string grad;

        public nastan(string naziv, string opis, string grad, string vreme)
        {
            this.naziv = naziv;
            this.opis = opis;
            this.grad = grad;
            this.vreme = vreme;
        }

        public int id_nastan { get; set; }
        public int fk_id_komintent { get; set; }
        public int o_id_objekt { get; set; }
        public string naziv { get; set; }
        public string vreme { get; set; }
        public string slika { get; set; }
        public string cas { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string kratok_opis { get; set; }
        public string sirok_opis { get; set; }
        public string sajt { get; set; }
        public string video { get; set; }
    
        public virtual komintent komintent { get; set; }
        public virtual objekt objekt { get; set; }
    }
}
