//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class statistika
    {
        public int id_statistika { get; set; }
        public string opis { get; set; }
        public string vreme { get; set; }
    }
}
